name: MLOps Student Placement Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: 

permissions:
  contents: write  # Memberi izin workflow untuk edit/upload file ke repo

jobs:
  process-and-update:
    runs-on: ubuntu-latest

    steps:
    # Checkout kode
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: main

    # Setup Python
    - name: Set up Python 3.12.7
      uses: actions/setup-python@v5
      with:
        python-version: "3.12.7"

    # Install Library
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas scikit-learn mlflow==2.19.0

    # Jalankan Preprocessing
    - name: Run Automate Script
      run: |
        cd preprocessing
        python automate_Budi.py

    # Commit dan Push Hasil
    - name: Commit and Push Processed Data
      run: |
        # Konfigurasi user git bot
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        
        # Tambahkan file hasil proses
        git add preprocessing/student_placement_clean.csv
        
        # Cek status, jika ada perubahan baru di-commit
        # "|| echo..." mencegah error jika tidak ada perubahan data
        git commit -m "Auto-update: Processed dataset by GitHub Actions" || echo "No changes to commit"
        
        # Upload balik ke GitHub
        git push